// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TKG.KenpinApp.Web.Data;

#nullable disable

namespace TKG.KenpinApp.Web.Migrations
{
    [DbContext(typeof(KenpinDbContext))]
    partial class KenpinDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.24");

            modelBuilder.Entity("TKG.KenpinApp.Web.Models.AppLog", b =>
                {
                    b.Property<long>("LogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("log_id");

                    b.Property<string>("ActionType")
                        .HasMaxLength(30)
                        .HasColumnType("TEXT")
                        .HasColumnName("action_type");

                    b.Property<string>("Detail")
                        .HasColumnType("TEXT")
                        .HasColumnName("detail");

                    b.Property<DateTime>("LogDatetime")
                        .HasColumnType("TEXT")
                        .HasColumnName("log_datetime");

                    b.Property<string>("ScreenId")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT")
                        .HasColumnName("screen_id");

                    b.Property<string>("UserCode")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT")
                        .HasColumnName("user_code");

                    b.HasKey("LogId");

                    b.HasIndex("LogDatetime");

                    b.HasIndex("UserCode");

                    b.ToTable("T_APP_LOG");
                });

            modelBuilder.Entity("TKG.KenpinApp.Web.Models.D365SyncQueue", b =>
                {
                    b.Property<long>("QueueId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("queue_id");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("completed_at");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<string>("LastError")
                        .HasColumnType("TEXT")
                        .HasColumnName("last_error");

                    b.Property<int>("MaxRetries")
                        .HasColumnType("INTEGER")
                        .HasColumnName("max_retries");

                    b.Property<DateTime?>("NextRetryAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("next_retry_at");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("payload");

                    b.Property<int>("RetryCount")
                        .HasColumnType("INTEGER")
                        .HasColumnName("retry_count");

                    b.Property<long>("SessionId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("session_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT")
                        .HasColumnName("status");

                    b.Property<string>("SyncType")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT")
                        .HasColumnName("sync_type");

                    b.HasKey("QueueId");

                    b.HasIndex("NextRetryAt");

                    b.HasIndex("SessionId");

                    b.HasIndex("Status");

                    b.ToTable("T_D365_SYNC_QUEUE");
                });

            modelBuilder.Entity("TKG.KenpinApp.Web.Models.DenpyoKenpin", b =>
                {
                    b.Property<long>("DenpyoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("denpyo_id");

                    b.Property<string>("Barcode")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("barcode");

                    b.Property<string>("DenpyoType")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT")
                        .HasColumnName("denpyo_type");

                    b.Property<string>("Result")
                        .HasMaxLength(10)
                        .HasColumnType("TEXT")
                        .HasColumnName("result");

                    b.Property<long>("SessionId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("session_id");

                    b.Property<DateTime?>("VerifiedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("verified_at");

                    b.HasKey("DenpyoId");

                    b.HasIndex("SessionId");

                    b.ToTable("T_DENPYO_KENPIN");
                });

            modelBuilder.Entity("TKG.KenpinApp.Web.Models.KenpinDetail", b =>
                {
                    b.Property<long>("DetailId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("detail_id");

                    b.Property<string>("Barcode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("barcode");

                    b.Property<DateTime?>("CancelDatetime")
                        .HasColumnType("TEXT")
                        .HasColumnName("cancel_datetime");

                    b.Property<bool>("CancelFlg")
                        .HasColumnType("INTEGER")
                        .HasColumnName("cancel_flg");

                    b.Property<string>("ItemCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("item_code");

                    b.Property<string>("KenpinCategory")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT")
                        .HasColumnName("kenpin_category");

                    b.Property<DateTime>("ScanDatetime")
                        .HasColumnType("TEXT")
                        .HasColumnName("scan_datetime");

                    b.Property<string>("ScanMethod")
                        .HasMaxLength(10)
                        .HasColumnType("TEXT")
                        .HasColumnName("scan_method");

                    b.Property<int>("ScanQty")
                        .HasColumnType("INTEGER")
                        .HasColumnName("scan_qty");

                    b.Property<long>("SessionId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("session_id");

                    b.HasKey("DetailId");

                    b.HasIndex("Barcode");

                    b.HasIndex("SessionId");

                    b.ToTable("T_KENPIN_DETAIL");
                });

            modelBuilder.Entity("TKG.KenpinApp.Web.Models.KenpinLock", b =>
                {
                    b.Property<long>("LockId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("lock_id");

                    b.Property<DateTime>("LockedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("locked_at");

                    b.Property<string>("LockedBy")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT")
                        .HasColumnName("locked_by");

                    b.Property<DateTime?>("ReleasedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("released_at");

                    b.Property<string>("SeiriNo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT")
                        .HasColumnName("seiri_no");

                    b.Property<DateTime>("ShukkaDate")
                        .HasColumnType("TEXT")
                        .HasColumnName("shukka_date");

                    b.Property<DateTime>("TimeoutAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("timeout_at");

                    b.HasKey("LockId");

                    b.HasIndex("SeiriNo", "ShukkaDate");

                    b.ToTable("T_KENPIN_LOCK");
                });

            modelBuilder.Entity("TKG.KenpinApp.Web.Models.KenpinSession", b =>
                {
                    b.Property<long>("SessionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("session_id");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("completed_at");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<bool>("D365Synced")
                        .HasColumnType("INTEGER")
                        .HasColumnName("d365_synced");

                    b.Property<string>("KenpinType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT")
                        .HasColumnName("kenpin_type");

                    b.Property<int>("ScannedQty")
                        .HasColumnType("INTEGER")
                        .HasColumnName("scanned_qty");

                    b.Property<string>("SeiriNo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT")
                        .HasColumnName("seiri_no");

                    b.Property<DateTime>("ShukkaDate")
                        .HasColumnType("TEXT")
                        .HasColumnName("shukka_date");

                    b.Property<string>("SiteCode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT")
                        .HasColumnName("site_code");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("started_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT")
                        .HasColumnName("status");

                    b.Property<int?>("TotalItems")
                        .HasColumnType("INTEGER")
                        .HasColumnName("total_items");

                    b.Property<int?>("TotalQty")
                        .HasColumnType("INTEGER")
                        .HasColumnName("total_qty");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at");

                    b.Property<string>("UserCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT")
                        .HasColumnName("user_code");

                    b.Property<string>("UserName")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("user_name");

                    b.Property<string>("WarehouseCode")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT")
                        .HasColumnName("warehouse_code");

                    b.HasKey("SessionId");

                    b.HasIndex("SeiriNo");

                    b.HasIndex("Status");

                    b.ToTable("T_KENPIN_SESSION");
                });

            modelBuilder.Entity("TKG.KenpinApp.Web.Models.UserSession", b =>
                {
                    b.Property<string>("SessionToken")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT")
                        .HasColumnName("session_token");

                    b.Property<DateTime?>("ExpiresAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("expires_at");

                    b.Property<DateTime?>("LoginAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("login_at");

                    b.Property<string>("SiteCode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT")
                        .HasColumnName("site_code");

                    b.Property<string>("UserCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT")
                        .HasColumnName("user_code");

                    b.Property<string>("UserName")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("user_name");

                    b.HasKey("SessionToken");

                    b.HasIndex("UserCode");

                    b.ToTable("T_USER_SESSION");
                });

            modelBuilder.Entity("TKG.KenpinApp.Web.Models.D365SyncQueue", b =>
                {
                    b.HasOne("TKG.KenpinApp.Web.Models.KenpinSession", "Session")
                        .WithMany()
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Session");
                });

            modelBuilder.Entity("TKG.KenpinApp.Web.Models.DenpyoKenpin", b =>
                {
                    b.HasOne("TKG.KenpinApp.Web.Models.KenpinSession", "Session")
                        .WithMany("DenpyoKenpins")
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Session");
                });

            modelBuilder.Entity("TKG.KenpinApp.Web.Models.KenpinDetail", b =>
                {
                    b.HasOne("TKG.KenpinApp.Web.Models.KenpinSession", "Session")
                        .WithMany("Details")
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Session");
                });

            modelBuilder.Entity("TKG.KenpinApp.Web.Models.KenpinSession", b =>
                {
                    b.Navigation("DenpyoKenpins");

                    b.Navigation("Details");
                });
#pragma warning restore 612, 618
        }
    }
}
